language: go
os: linux

jobs:
  include:
    - stage: Build
      name: Server
      before_install:
        - cd server
      install: skip
      script: 
        - env GO111MODULE=on go build
    - stage: Test
      name: Server
      before_install:
        - cd server
      install: skip
      script:
        - env GO111MODULE=on go test ./... -v -cover
