language: go
os: linux
dist: bionic
env:
  - GO111MODULE=on CFG_ENV=travis COVERALLS_PARALLEL=true
go:
  - 1.14.x
notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:
    - stage: Build
      name: Build Server
      before_install:
        - cd server
      install: skip
      script: 
        - go build
    - name: Build Migration Runner
      before_install:
        - cd server/database/migration_runner
      install: skip
      script: 
        - go build
    - stage: Test
      name: Server Unit Tests
      before_install:
        - cd server
      install:
        - go get github.com/mattn/goveralls
      script:
        - go test ./models/ -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - name: Migration Runner Unit Tests
      before_install:
        - cd common/migration_runner
      install:
        - go get github.com/mattn/goveralls
      script:
        - go test -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - name: Mongo Adapter Integration Tests
      services:
        - mongodb
      before_install:
        - cd server/database/mongo_adapter
      install:
        - go get github.com/mattn/goveralls
      script:
        - go test -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
