language: go
os: linux

jobs:
  include:
    - stage: Build
      name: Server
      install: skip
      script: 
        - go build server/main.go
    - stage: Test
      name: Server
      install: skip
      script:
        - go test ./server/... -v -cover
