// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordCriteriaValidator is an autogenerated mock type for the PasswordCriteriaValidator type
type PasswordCriteriaValidator struct {
	mock.Mock
}

// ValidatePasswordCriteria provides a mock function with given fields: password
func (_m *PasswordCriteriaValidator) ValidatePasswordCriteria(password string) error {
	ret := _m.Called(password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
