// Code generated by mockery v1.1.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	httprouter "github.com/julienschmidt/httprouter"
	mock "github.com/stretchr/testify/mock"
)

// RequestHandler is an autogenerated mock type for the RequestHandler type
type RequestHandler struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *RequestHandler) DeleteUser(_a0 http.ResponseWriter, _a1 *http.Request, _a2 httprouter.Params) {
	_m.Called(_a0, _a1, _a2)
}

// PatchUserPassword provides a mock function with given fields: _a0, _a1, _a2
func (_m *RequestHandler) PatchUserPassword(_a0 http.ResponseWriter, _a1 *http.Request, _a2 httprouter.Params) {
	_m.Called(_a0, _a1, _a2)
}

// PostUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *RequestHandler) PostUser(_a0 http.ResponseWriter, _a1 *http.Request, _a2 httprouter.Params) {
	_m.Called(_a0, _a1, _a2)
}
